### ISSUE TITLE
Ubuntu 16.04 fails on start-up

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/makehuman_python3#12]
Log from Ubuntu 16.04 startup at rev 7f66efa6c44279561d1bf15d5cf9bc9554b272b3

Detected HG revision: r? (UNKNOWN)
Initialized logging
VERSION: 1.2.0 (r? UNKNOWN) [none found]
HG REVISION: r? (UNKNOWN) [none found]
SHORT VERSION: v1.2.0
BASEMESH VERSION: hm08
IS BUILT (FROZEN): No
IS RELEASE VERSION: No
WORKING DIRECTORY: /home/joepal/source/makehuman_python3/makehuman
HOME LOCATION: /home/joepal
PYTHON PATH: ./:./lib:./apps:./shared:./apps/gui:./core:/home/joepal/source/makehuman_python3/makehuman:/usr/lib/python35.zip:/usr/lib/python3.5:/usr/lib/python3.5/plat-x86_64-linux-gnu:/usr/lib/python3.5/lib-dynload:/usr/local/lib/python3.5/dist-packages:/usr/lib/python3/dist-packages
DLL PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/joepal/system/bin
SYS.VERSION: 3.5.1+ (default, Mar 30 2016, 22:46:26)  [GCC 5.3.1 20160330]
SYS.PLATFORM: linux
SYS.EXECUTABLE: /usr/bin/python3
PLATFORM.MACHINE: x86_64
PLATFORM.PROCESSOR: x86_64
PLATFORM.UNAME.RELEASE: 4.4.0-31-generic
NUMPY.VERSION: 1.11.0
No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
Unable to load registered array format handler numeric
Traceback (most recent call last):
  File "makehuman.py", line 827, in <module>
    main()
  File "makehuman.py", line 817, in main
    from mhmain import MHApplication
  File "./core/mhmain.py", line 45, in <module>
    import mh
  File "./lib/mh.py", line 43, in <module>
    from glmodule import grabScreen, hasRenderSkin, renderSkin, getPickedColor, hasRenderToRenderbuffer, renderToBuffer, renderAlphaMask
  File "./lib/glmodule.py", line 47, in <module>
    from OpenGL.GL import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/__init__.py", line 22, in <module>
    formathandler.FormatHandler.loadAll()
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 28, in loadAll
    cls.loadPlugin( entrypoint )
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/vbo.py", line 430, in <module>
    def mapVBO( vbo, access=GL.GL_READ_WRITE ):
AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'

**Comment by joepal1976** [comment]
Exact package versions in ubuntu 16.04

    python3                         3.5.1-3
    python3-numpy                   1:1.11.0-1ubuntu1
    python3-opengl                  3.0.2-1
    python3-pyqt4                   4.11.4+dfsg-1build4
    python3-pyqt4.qtopengl          4.11.4+dfsg-1build4

**Comment by rwbaer** [comment]
Some ideas/discussion to consider working around this if it is indeed a Python 3.5 thing:
http://bugs.python.org/issue26245
https://ubuntu-mate.community/t/pi3-v16-04-python3-opengl-problem/5138/2

The first begs the question of whether Python 3.4 gets farther on Ubuntu 16.04. It also implies/hints that 
from OpenGL.GLU import *
from OpenGL.GL import *

might be more effective than the other way around in glmodule.py lines 47 & 48.  No harm in trying. See revision c8517130c56529f92041a0478f6c3589225e6770

**Comment by rwbaer** [comment]
Aspire box:  Linux 16.04 with mesa driver results:
sudo apt-get install libegl1-mesa libegl1-mesa-drivers xserver-xorg-video-intel libgl1-mesa-dri libglapi-mesa 

rwbaer@Aspire:~/MHPY3-GIT/makehuman$ python3 makehuman.py
MakeHuman Copyright (C) 2001-2016 http://www.makehuman.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions. For details use the option --license

NO VERSION file detected, retrieving revision info from HG
abort: no repository found in '/home/rwbaer/MHPY3-GIT' (.hg not found)!
NOTICE: Failed to get hg version number from command line: a bytes-like object is required, not 'str' (This is just a head's up, not a critical error)
NOTICE: Failed to get hg version number using hglib: No module named 'hglib' (This is just a head's up, not a critical error)
NOTICE: Failed to get hg parent version from dirstate file: [Errno 2] No such file or directory: '/home/rwbaer/MHPY3-GIT/.hg/dirstate' (This is just a head's up, not a critical error)
NOTICE: Failed to get hg tip version from cache file: [Errno 2] No such file or directory: '/home/rwbaer/MHPY3-GIT/.hg/cache/tags' (This is just a head's up, not a critical error)
Detected HG revision: r? (UNKNOWN)
Initialized logging
VERSION: 1.2.0 (r? UNKNOWN) [none found]
HG REVISION: r? (UNKNOWN) [none found]
SHORT VERSION: v1.2.0
BASEMESH VERSION: hm08
IS BUILT (FROZEN): No
IS RELEASE VERSION: No
WORKING DIRECTORY: /home/rwbaer/MHPY3-GIT/makehuman
HOME LOCATION: /home/rwbaer
PYTHON PATH: ./:./lib:./apps:./shared:./apps/gui:./core:/home/rwbaer/MHPY3-GIT/makehuman:/usr/lib/python35.zip:/usr/lib/python3.5:/usr/lib/python3.5/plat-x86_64-linux-gnu:/usr/lib/python3.5/lib-dynload:/home/rwbaer/.local/lib/python3.5/site-packages:/usr/local/lib/python3.5/dist-packages:/usr/lib/python3/dist-packages
DLL PATH: /home/rwbaer/workspace/rnaseq/tools/samtools-1.1:/home/rwbaer/workspace/rnaseq/tools/bam-readcount/bin:/home/rwbaer/workspace/rnaseq/tools/bowtie2-2.2.4:/home/rwbaer/workspace/rnaseq/tools/tophat-2.0.13.Linux_x86_64:/home/rwbaer/workspace/rnaseq/tools/STAR-STAR_2.4.0f1/source:/home/rwbaer/workspace/rnaseq/tools/cufflinks-2.2.1.Linux_x86_64:/home/rwbaer/workspace/rnaseq/tools/HTSeq-0.6.1p1/scripts:/home/rwbaer/workspace/rnaseq/R-3.1.0/bin:/home/rwbaer/workspace/rnaseq/tools/FastQC:/home/rwbaer/workspace/rnaseq/tools/picard-tools-1.124:/home/rwbaer/workspace/rnaseq/tools/samstat-1.5/src:/home/ubuntu/bin/bedtools2/bin:/home/rwbaer/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
SYS.VERSION: 3.5.2 (default, Jul  5 2016, 12:43:10)  [GCC 5.4.0 20160609]
SYS.PLATFORM: linux
SYS.EXECUTABLE: /usr/bin/python3
PLATFORM.MACHINE: x86_64
PLATFORM.PROCESSOR: x86_64
PLATFORM.UNAME.RELEASE: 4.4.0-31-generic
NUMPY.VERSION: 1.11.1
Traceback (most recent call last):
  File "makehuman.py", line 827, in <module>
    main()
  File "makehuman.py", line 817, in main
    from mhmain import MHApplication
  File "./core/mhmain.py", line 45, in <module>
    import mh
  File "./lib/mh.py", line 43, in <module>
    from glmodule import grabScreen, hasRenderSkin, renderSkin, getPickedColor, hasRenderToRenderbuffer, renderToBuffer, renderAlphaMask
  File "./lib/glmodule.py", line 42, in <module>
    import OpenGL
ImportError: No module named 'OpenGL'
rwbaer@Aspire:~/MHPY3-GIT/makehuman$ sudo apt install mesa-utils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mesa-utils is already the newest version (8.3.0-1).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
rwbaer@Aspire:~/MHPY3-GIT/makehuman$ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 12.1.0-devel
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 12.1.0-devel
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 12.1.0-devel
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

**Comment by joepal1976** [comment]
You'll also need the python bindings. I made a bash script for installing those: 

https://github.com/makehumancommunity/makehuman_python3/blob/master/buildscripts/deb/install_deb_dependencies.bash

But every mention of "python" in that should be replaced with "python3".

**Comment by rwbaer** [comment]
For the record, this "dependency set" did not achieve the desired result for me:
------------------------------------------------------------------------------------------------
rwbaer@Aspire:~/MHPY3-GIT/makehuman$ sudo apt-get install python3 python3-numpy python3-opengl python3-qt4 python3-qt4-gl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-qt4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'python3-qt4' has no installation candidate
E: Unable to locate package python3-qt4-gl
-------------------------------------------------------------------------------------------------------------------------------------------



Here's what does seem to work and gets me a splash screen and almost to the issues I'm working on the Windows side:

rwbaer@Aspire:~/MHPY3-GIT/makehuman$ sudo apt-get update
rwbaer@Aspire:~/MHPY3-GIT/makehuman$ sudo apt-get install python3-pyqt4.qtopengl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  python3-pyqt4.qtopengl
0 upgraded, 1 newly installed, 0 to remove and 51 not upgraded.
Need to get 63.5 kB of archives.
After this operation, 345 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 python3-pyqt4.qtopengl amd64 4.11.4+dfsg-1build4 [63.5 kB]
Fetched 63.5 kB in 0s (217 kB/s)                
Selecting previously unselected package python3-pyqt4.qtopengl.
(Reading database ... 332143 files and directories currently installed.)
Preparing to unpack .../python3-pyqt4.qtopengl_4.11.4+dfsg-1build4_amd64.deb ...
Unpacking python3-pyqt4.qtopengl (4.11.4+dfsg-1build4) ...
Setting up python3-pyqt4.qtopengl (4.11.4+dfsg-1build4) ...
-------------------------------------------------------------------------------------------------------------------------------------------

AND starting  MAKEHUMAN  ...

rwbaer@Aspire:~/MHPY3-GIT/makehuman$ python3 makehuman.py
MakeHuman Copyright (C) 2001-2016 http://www.makehuman.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions. For details use the option --license

NO VERSION file detected, retrieving revision info from HG
abort: no repository found in '/home/rwbaer/MHPY3-GIT' (.hg not found)!
NOTICE: Failed to get hg version number from command line: a bytes-like object is required, not 'str' (This is just a head's up, not a critical error)
NOTICE: Failed to get hg version number using hglib: No module named 'hglib' (This is just a head's up, not a critical error)
NOTICE: Failed to get hg parent version from dirstate file: [Errno 2] No such file or directory: '/home/rwbaer/MHPY3-GIT/.hg/dirstate' (This is just a head's up, not a critical error)
NOTICE: Failed to get hg tip version from cache file: [Errno 2] No such file or directory: '/home/rwbaer/MHPY3-GIT/.hg/cache/tags' (This is just a head's up, not a critical error)
Detected HG revision: r? (UNKNOWN)
Initialized logging
VERSION: 1.2.0 (r? UNKNOWN) [none found]
HG REVISION: r? (UNKNOWN) [none found]
SHORT VERSION: v1.2.0
BASEMESH VERSION: hm08
IS BUILT (FROZEN): No
IS RELEASE VERSION: No
WORKING DIRECTORY: /home/rwbaer/MHPY3-GIT/makehuman
HOME LOCATION: /home/rwbaer
PYTHON PATH: ./:./lib:./apps:./shared:./apps/gui:./core:/home/rwbaer/MHPY3-GIT/makehuman:/usr/lib/python35.zip:/usr/lib/python3.5:/usr/lib/python3.5/plat-x86_64-linux-gnu:/usr/lib/python3.5/lib-dynload:/home/rwbaer/.local/lib/python3.5/site-packages:/usr/local/lib/python3.5/dist-packages:/usr/lib/python3/dist-packages
DLL PATH: /home/rwbaer/workspace/rnaseq/tools/samtools-1.1:/home/rwbaer/workspace/rnaseq/tools/bam-readcount/bin:/home/rwbaer/workspace/rnaseq/tools/bowtie2-2.2.4:/home/rwbaer/workspace/rnaseq/tools/tophat-2.0.13.Linux_x86_64:/home/rwbaer/workspace/rnaseq/tools/STAR-STAR_2.4.0f1/source:/home/rwbaer/workspace/rnaseq/tools/cufflinks-2.2.1.Linux_x86_64:/home/rwbaer/workspace/rnaseq/tools/HTSeq-0.6.1p1/scripts:/home/rwbaer/workspace/rnaseq/R-3.1.0/bin:/home/rwbaer/workspace/rnaseq/tools/FastQC:/home/rwbaer/workspace/rnaseq/tools/picard-tools-1.124:/home/rwbaer/workspace/rnaseq/tools/samstat-1.5/src:/home/ubuntu/bin/bedtools2/bin:/home/rwbaer/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
SYS.VERSION: 3.5.2 (default, Jul  5 2016, 12:43:10)  [GCC 5.4.0 20160609]
SYS.PLATFORM: linux
SYS.EXECUTABLE: /usr/bin/python3
PLATFORM.MACHINE: x86_64
PLATFORM.PROCESSOR: x86_64
PLATFORM.UNAME.RELEASE: 4.4.0-31-generic
NUMPY.VERSION: 1.11.1
No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
Unable to load registered array format handler numeric
PYQT.VERSION: 4.8.7
PYQT.JPG_SUPPORT: not supported
PYQT.SVG_SUPPORT: not supported
QT.PLUGIN_PATH: /usr/lib/x86_64-linux-gnu/qt4/plugins:/usr/bin
QT.PLUGIN_PATH_ENV: 
QT.CONF: NOT PRESENT
GL.VENDOR: b'Intel Open Source Technology Center'
GL.RENDERER: b'Mesa DRI Intel(R) Haswell Mobile '
GL.VERSION: b'3.0 Mesa 12.1.0-devel'
OpenGL Version: b'3.0 Mesa 12.1.0-devel'
1.30
GLSL.VERSION: b'1.30'
GL Extension b'GL_ARB_multisample' available
GL.EXTENSION: GL_ARB_multisample enabled (4x samples)
Creating new texture for image data/textures/texture_notfound.png.
GL Extension b'GL_ARB_texture_non_power_of_two' available
GL.EXTENSION: GL_ARB_texture_non_power_of_two enabled
initTexture: 256, 256, False
Setting language to english
No settings file found, starting with default settings.
Setting language to english
shortcuts.ini out of date; ignoring
Initializing default theme first.
Theme default version 1.1.0
Loaded theme data/themes/default.mht
Using Qt system style gtk+
Loading human
Loading binary mesh data/3dobjs/base.npz.
Loading material from file data/skins/default.mhmat
Exception during event onStart
Traceback (most recent call last):
  File "./core/events3d.py", line 219, in callEvent
    method(event)
  File "./core/mhmain.py", line 811, in onStart
    self.startupSequence()
  File "./core/mhmain.py", line 733, in startupSequence
    self.loadHuman()
  File "./core/mhmain.py", line 384, in loadHuman
    self.selectedHuman = self.addObject(human.Human(files3d.loadMesh(mh.getSysDataPath("3dobjs/base.obj"), maxFaces = 5)))
  File "./apps/human.py", line 82, in __init__
    self.material = material.fromFile(getSysDataPath('skins/default.mhmat'))
  File "./shared/material.py", line 1374, in fromFile
    mat.fromFile(filename)
  File "./shared/material.py", line 478, in fromFile
    self.configureShading(diffuse=shaderConfig_diffuse, bump=shaderConfig_bump, normal=shaderConfig_normal, displacement=shaderConfig_displacement, spec=shaderConfig_spec, vertexColors=shaderConfig_vertexColors, transparency=shaderConfig_transparency, ambientOcclusion=shaderConfig_ambientOcclusion)
  File "./shared/material.py", line 915, in configureShading
    self._updateShaderConfig()
  File "./shared/material.py", line 952, in _updateShaderConfig
    bump = self._shaderConfig['bump'] and self.supportsBump()
  File "./shared/material.py", line 847, in supportsBump
    if self.shaderObj and result:
  File "./shared/material.py", line 1012, in shaderObj
    return self.getShaderObj()
  File "./shared/material.py", line 1008, in getShaderObj
    return shader.getShader(shaderPath, self.shaderDefines)
  File "./lib/shader.py", line 519, in getShader
    shader = Shader(path, defines)
  File "./lib/shader.py", line 310, in __init__
    self.initShader()
  File "./lib/shader.py", line 433, in initShader
    self.vertexTangentAttrId = glGetAttribLocation(self.shaderId, 'tangent')
  File "/usr/lib/python3/dist-packages/OpenGL/latebind.py", line 61, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/usr/lib/python3/dist-packages/OpenGL/GL/VERSION/GL_2_0.py", line 229, in glGetAttribLocation
    name = name + _NULL_8_BYTE
TypeError: Can't convert 'bytes' object to str implicitly

** I now get a splash screen  that hangs **

In general, openGL likes to work with BYTES but  on occasion passes back strings.  Obviously, the behavior of the latter is / can be different by default in Python 3.  Nicely, the Linux "fail' comes with clearer context than the corresponding Windows "fail".  

Let's see if this contributes to directed progress.

**Comment by rwbaer** [comment]
Happy to report I can now get beyond the startup screen (nudity warning and all) to a partially working GUI on the Linux side.  In fact, the feet on floor problem I'm experiencing on the Windows side is not an issue on Linux.

**Comment by joepal1976** [comment]
That is great news. :-)

Could I convince you to write a blog post about your progress and your experiences so far? I think you have access to the blog function on the community site front page.

**Comment by rwbaer** [comment]
I'm glad to write something, but I'd like just a little more time to see if I can solve the shader issue (at least partly).  Here is the difference between the litesphere shader and no shader.  Further, although the feet are on the ground on the linux side and the high poly eyes load, this is still not the case on the Windows side.   Here's the shader problem illustrated:
 
![image](https://cloud.githubusercontent.com/assets/3155051/17628982/8f9520ea-607d-11e6-90d9-43e8c9163ea9.png)

**Comment by rwbaer** [comment]
Since startup works, and the shader is at least seemingly operational, the ubuntu version seems caught up so closing this. New problems will get new iisue
