### ISSUE TITLE
Python 2's freeze and Python 3 future 

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/makehuman_python3#9]
Guido von Rossum on Python present and future (25th aniversery):
https://www.youtube.com/watch?v=YgtL4S7Hrwo

And BTW, Python development is moving from Mercurial to GIT, late 2016 -- go figure!

**Comment by joepal1976** [comment]
Soon only MakeHuman will remain in mercurial. :-)

**Comment by rwbaer** [comment]
This issue was just for "project rationale" purposes and has served its purpose as a reference
